on:
  - push
  - workflow_dispatch

jobs:
  test-job:
    runs-on: ubuntu-latest
    name: Github action test job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test my action
        id: yaml-action
        uses: teunmooij/yaml@main
        with:
          data: >
            {
              "test": "test"
            }
      - name: Use data
        run: echo "Data ${{ steps.yaml-action.outputs.data }}"
